### ISSUE TITLE
Organize Packaging Files & Optimize Release files

### ISSUE THREAD

**Issue by UpCloudHost** [Nxium-Developments/NextLanguage#1]
## GH Source Code Organizing
Organize the Source files into an folder, separate of the Github and other packaging files.

**Folders***
Put the files into an separate folder for its purpose.

## Release Files Size
We will have to optimize the releaee packages and remove unnecessary files, during setup and
download.

**List of Unnecessary Files**
- Copies of setup files on /data/ folder
- Copies of setup files in other modules

**Solutions to problems**
Make the modules download it from github instead of copying them from an ready made files.
And remove modules that are no needs like the disabled ones.

**Comment by RBLAuthorizations** [comment]
Completed, check the [latest release here](https://github.com/Nxium-Developments/NextLanguage/releases/tag/v1.1)
