### ISSUE TITLE
Creating Simple Syntax

### ISSUE THREAD

**Issue by AshleyNex** [Nxium-Developments/NextLanguage#2]
## Notes for Feature
Making simple sytanx for creating securities system

**Syntaxes**
- secure (For securing connections, passwords, and rooting systems)
Maybe I'll add morensoon

**Syntax Tree**
1. secure
	- secure.test (For testing the connection if it is secured or not)
	- secure.connection(id: connectionid, testid-OPTIONAL: true or false, connect: true or false) (Is for connecting to the id)
	- secure.create:id (Is for creating an connection id)
	- secure.create:key(privatekey: true or false, publickey: true or false, bothkey: true or false) (if you set bothkeys to true then there is no need for setting the other two)
	- secure.delete:key(id: keyid) (Is for deleting the key, with its id)
	- secure.delete:cid (id: connectionid) (Is for deleting the connection id)

**Comment by LightmachjneRYAN** [comment]
NXIUM development still on?

**Comment by RBLAuthorizations** [comment]
> NXIUM development still on?

Yes, we are developing NextLanguage

**Comment by LightmachjneRYAN** [comment]
> @LightmachjneRYAN would you like to collaborate on this

I am taking a look before i start

**Comment by LightmachjneRYAN** [comment]
What will the project be used for

**Comment by GustyCube** [comment]
@LightmachjneRYAN has your discord been hacked?
