### ISSUE TITLE
Update README File Example code

### ISSUE THREAD

**Issue by AshleyAst** [Nxium-Developments/NextLanguage#3]
The part of the README file saying ``const { executeNxlFile } = require('@nyxast/nextlanguage')`` should be changed to
``const { runJavascript } = require('@nyxast/nextlanguage')`` as the code has been updated to that reference soon after
the v1.7.2 on the [NPM repositories](https://www.npmjs.com/package/@nyxast/nextlanguage?activeTab=versions) which also shows that this github repo has been severely outdated from the new versions released to the NPM Repo instead of being released here as well

If this issue won't be resolved within the next few days, I will create an fork of this repo and update it.

**Comment by AshleyNex** [comment]
We're aware of this issue and will be fixed as soon as it is approved by our approval team

**Comment by AshleyNex** [comment]
It has just been approved and it should be fixed within a few moments

**Comment by AshleyAst** [comment]
It has been fixed thank you
